export enum USER_CONSTANTS {
  USER_FETCH = "USER_FETCH",
  USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS",
  USER_FETCH_ERROR = "USER_FETCH_ERROR",
}

export enum PRODUCT_CONSTANTS {
  PRODUCT_FETCH = "PRODUCT_FETCH",
  PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS",
  PRODUCT_FETCH_ERROR = "PRODUCT_FETCH_ERROR",
}
